In [45]:
# first question
import psycopg2

#establishing the connection
conn = psycopg2.connect(
   database='dvdrental', user='postgres', password='1', host='127.0.0.1', port= '5432'
)
cursor = conn.cursor()

sql ='''
    CREATE EXTENSION IF NOT EXISTS tablefunc;
    select * from crosstab(
        'select  c.name, s.store_id, count(r.rental_id)
        from rental r 
        left join inventory i on i.inventory_id=r.inventory_id
        left join store s on s.store_id=i.store_id 
        left join film f on f.film_id=i.film_id
        left join film_category fc on fc.film_id=f.film_id
        left join category c on c.category_id=fc.category_id
        GROUP BY s.store_id, c.name',
        'select m from generate_series(1,2) m'
    ) as (
    name varchar,
    "store_1" int,
    "store_2" int
    );
    
'''
cursor.execute(sql)

col_names = []
for elt in cursor.description:
    col_names.append(elt[0])
print(col_names)
result = cursor.fetchall()
for i in result:
    print(i)

conn.close()

['name', 'store_1', 'store_2']
('Sports', 555, None)
('Sci-Fi', 521, None)
('Horror', 386, None)
('Animation', None, 598)
('Documentary', None, 600)
('Classics', 447, None)
('Comedy', None, 439)
('Sports', None, 624)
('Horror', None, 460)
('Documentary', 450, None)
('New', None, 438)
('Action', None, 516)
('Family', None, 539)
('Foreign', None, 509)
('Music', 436, 394)
('Children', 453, None)
('Games', 455, None)
('Animation', 568, None)
('Drama', 576, None)
('Comedy', 502, None)
('Sci-Fi', None, 580)
('Foreign', 524, None)
('Classics', None, 492)
('New', 502, None)
('Travel', 395, None)
('Children', None, 492)
('Action', 596, None)
('Travel', None, 442)
('Drama', None, 484)
('Games', None, 514)
('Family', 557, None)

In [14]:
# second question
import psycopg2


#establishing the connection
conn = psycopg2.connect(
   database='dvdrental', user='postgres', password='1', host='127.0.0.1', port= '5432'
)
cursor = conn.cursor()

sql ='''
    select 
    
    case grouping(year)
        when 0 then year
        when 1 then NULL
        end as year,
    case grouping(month)
        when 0 then month
        when 1 then NULL
        end as month,
    case grouping(day)
        when 0 then day
        when 1 then NULL
        end as day,
    sum(amount) from
        (select amount, EXTRACT(YEAR FROM payment_date) as year,
        EXTRACT(MONTH FROM payment_date) as month,
        EXTRACT(DAY FROM payment_date) as day
        from payment) as inner_query
    group by rollup(year, month, day);
    
'''
cursor.execute(sql)

col_names = []
for elt in cursor.description:
    col_names.append(elt[0])
print(col_names)
result = cursor.fetchall()
for i in result:
    print(i)

conn.close()

['year', 'month', 'day', 'sum']
(Decimal('2007'), Decimal('2'), Decimal('14'), Decimal('116.73'))
(Decimal('2007'), Decimal('2'), Decimal('15'), Decimal('1188.92'))
(Decimal('2007'), Decimal('2'), Decimal('16'), Decimal('1154.18'))
(Decimal('2007'), Decimal('2'), Decimal('17'), Decimal('1188.17'))
(Decimal('2007'), Decimal('2'), Decimal('18'), Decimal('1275.98'))
(Decimal('2007'), Decimal('2'), Decimal('19'), Decimal('1290.90'))
(Decimal('2007'), Decimal('2'), Decimal('20'), Decimal('1219.09'))
(Decimal('2007'), Decimal('2'), Decimal('21'), Decimal('917.87'))
(Decimal('2007'), Decimal('2'), None, Decimal('8351.84'))
(Decimal('2007'), Decimal('3'), Decimal('1'), Decimal('2808.24'))
(Decimal('2007'), Decimal('3'), Decimal('2'), Decimal('2550.05'))
(Decimal('2007'), Decimal('3'), Decimal('16'), Decimal('299.28'))
(Decimal('2007'), Decimal('3'), Decimal('17'), Decimal('2442.16'))
(Decimal('2007'), Decimal('3'), Decimal('18'), Decimal('2701.76'))
(Decimal('2007'), Decimal('3'), Decimal('19'), Decimal('2617.69'))
(Decimal('2007'), Decimal('3'), Decimal('20'), Decimal('2669.89'))
(Decimal('2007'), Decimal('3'), Decimal('21'), Decimal('2868.27'))
(Decimal('2007'), Decimal('3'), Decimal('22'), Decimal('2586.79'))
(Decimal('2007'), Decimal('3'), Decimal('23'), Decimal('2342.43'))
(Decimal('2007'), Decimal('3'), None, Decimal('23886.56'))
(Decimal('2007'), Decimal('4'), Decimal('5'), Decimal('273.36'))
(Decimal('2007'), Decimal('4'), Decimal('6'), Decimal('2077.14'))
(Decimal('2007'), Decimal('4'), Decimal('7'), Decimal('1984.28'))
(Decimal('2007'), Decimal('4'), Decimal('8'), Decimal('2227.84'))
(Decimal('2007'), Decimal('4'), Decimal('9'), Decimal('2067.86'))
(Decimal('2007'), Decimal('4'), Decimal('10'), Decimal('1973.18'))
(Decimal('2007'), Decimal('4'), Decimal('11'), Decimal('1940.32'))
(Decimal('2007'), Decimal('4'), Decimal('12'), Decimal('1930.48'))
(Decimal('2007'), Decimal('4'), Decimal('26'), Decimal('347.21'))
(Decimal('2007'), Decimal('4'), Decimal('27'), Decimal('2673.57'))
(Decimal('2007'), Decimal('4'), Decimal('28'), Decimal('2622.73'))
(Decimal('2007'), Decimal('4'), Decimal('29'), Decimal('2717.60'))
(Decimal('2007'), Decimal('4'), Decimal('30'), Decimal('5723.89'))
(Decimal('2007'), Decimal('4'), None, Decimal('28559.46'))
(Decimal('2007'), Decimal('5'), Decimal('14'), Decimal('514.18'))
(Decimal('2007'), Decimal('5'), None, Decimal('514.18'))
(Decimal('2007'), None, None, Decimal('61312.04'))
(None, None, None, Decimal('61312.04'))

In [15]:
# third question
import psycopg2


#establishing the connection
conn = psycopg2.connect(
   database='dvdrental', user='postgres', password='1', host='127.0.0.1', port= '5432'
)
cursor = conn.cursor()

sql ='''
    select 
    
    case grouping(year)
        when 0 then year
        when 1 then NULL
        end as year,
    case grouping(month)
        when 0 then month
        when 1 then NULL
        end as month,
    case grouping(day)
        when 0 then day
        when 1 then NULL
        end as day,
    sum(amount) from
        (select amount, EXTRACT(YEAR FROM payment_date) as year,
        EXTRACT(MONTH FROM payment_date) as month,
        EXTRACT(DAY FROM payment_date) as day
        from payment) as inner_query
    group by cube(year, month, day);
    
'''
cursor.execute(sql)

col_names = []
for elt in cursor.description:
    col_names.append(elt[0])
print(col_names)
result = cursor.fetchall()
for i in result:
    print(i)

conn.close()

['year', 'month', 'day', 'sum']
(Decimal('2007'), Decimal('2'), Decimal('14'), Decimal('116.73'))
(Decimal('2007'), Decimal('2'), Decimal('15'), Decimal('1188.92'))
(Decimal('2007'), Decimal('2'), Decimal('16'), Decimal('1154.18'))
(Decimal('2007'), Decimal('2'), Decimal('17'), Decimal('1188.17'))
(Decimal('2007'), Decimal('2'), Decimal('18'), Decimal('1275.98'))
(Decimal('2007'), Decimal('2'), Decimal('19'), Decimal('1290.90'))
(Decimal('2007'), Decimal('2'), Decimal('20'), Decimal('1219.09'))
(Decimal('2007'), Decimal('2'), Decimal('21'), Decimal('917.87'))
(Decimal('2007'), Decimal('2'), None, Decimal('8351.84'))
(Decimal('2007'), Decimal('3'), Decimal('1'), Decimal('2808.24'))
(Decimal('2007'), Decimal('3'), Decimal('2'), Decimal('2550.05'))
(Decimal('2007'), Decimal('3'), Decimal('16'), Decimal('299.28'))
(Decimal('2007'), Decimal('3'), Decimal('17'), Decimal('2442.16'))
(Decimal('2007'), Decimal('3'), Decimal('18'), Decimal('2701.76'))
(Decimal('2007'), Decimal('3'), Decimal('19'), Decimal('2617.69'))
(Decimal('2007'), Decimal('3'), Decimal('20'), Decimal('2669.89'))
(Decimal('2007'), Decimal('3'), Decimal('21'), Decimal('2868.27'))
(Decimal('2007'), Decimal('3'), Decimal('22'), Decimal('2586.79'))
(Decimal('2007'), Decimal('3'), Decimal('23'), Decimal('2342.43'))
(Decimal('2007'), Decimal('3'), None, Decimal('23886.56'))
(Decimal('2007'), Decimal('4'), Decimal('5'), Decimal('273.36'))
(Decimal('2007'), Decimal('4'), Decimal('6'), Decimal('2077.14'))
(Decimal('2007'), Decimal('4'), Decimal('7'), Decimal('1984.28'))
(Decimal('2007'), Decimal('4'), Decimal('8'), Decimal('2227.84'))
(Decimal('2007'), Decimal('4'), Decimal('9'), Decimal('2067.86'))
(Decimal('2007'), Decimal('4'), Decimal('10'), Decimal('1973.18'))
(Decimal('2007'), Decimal('4'), Decimal('11'), Decimal('1940.32'))
(Decimal('2007'), Decimal('4'), Decimal('12'), Decimal('1930.48'))
(Decimal('2007'), Decimal('4'), Decimal('26'), Decimal('347.21'))
(Decimal('2007'), Decimal('4'), Decimal('27'), Decimal('2673.57'))
(Decimal('2007'), Decimal('4'), Decimal('28'), Decimal('2622.73'))
(Decimal('2007'), Decimal('4'), Decimal('29'), Decimal('2717.60'))
(Decimal('2007'), Decimal('4'), Decimal('30'), Decimal('5723.89'))
(Decimal('2007'), Decimal('4'), None, Decimal('28559.46'))
(Decimal('2007'), Decimal('5'), Decimal('14'), Decimal('514.18'))
(Decimal('2007'), Decimal('5'), None, Decimal('514.18'))
(Decimal('2007'), None, None, Decimal('61312.04'))
(None, None, None, Decimal('61312.04'))
(None, Decimal('2'), Decimal('14'), Decimal('116.73'))
(None, Decimal('2'), Decimal('15'), Decimal('1188.92'))
(None, Decimal('2'), Decimal('16'), Decimal('1154.18'))
(None, Decimal('2'), Decimal('17'), Decimal('1188.17'))
(None, Decimal('2'), Decimal('18'), Decimal('1275.98'))
(None, Decimal('2'), Decimal('19'), Decimal('1290.90'))
(None, Decimal('2'), Decimal('20'), Decimal('1219.09'))
(None, Decimal('2'), Decimal('21'), Decimal('917.87'))
(None, Decimal('2'), None, Decimal('8351.84'))
(None, Decimal('3'), Decimal('1'), Decimal('2808.24'))
(None, Decimal('3'), Decimal('2'), Decimal('2550.05'))
(None, Decimal('3'), Decimal('16'), Decimal('299.28'))
(None, Decimal('3'), Decimal('17'), Decimal('2442.16'))
(None, Decimal('3'), Decimal('18'), Decimal('2701.76'))
(None, Decimal('3'), Decimal('19'), Decimal('2617.69'))
(None, Decimal('3'), Decimal('20'), Decimal('2669.89'))
(None, Decimal('3'), Decimal('21'), Decimal('2868.27'))
(None, Decimal('3'), Decimal('22'), Decimal('2586.79'))
(None, Decimal('3'), Decimal('23'), Decimal('2342.43'))
(None, Decimal('3'), None, Decimal('23886.56'))
(None, Decimal('4'), Decimal('5'), Decimal('273.36'))
(None, Decimal('4'), Decimal('6'), Decimal('2077.14'))
(None, Decimal('4'), Decimal('7'), Decimal('1984.28'))
(None, Decimal('4'), Decimal('8'), Decimal('2227.84'))
(None, Decimal('4'), Decimal('9'), Decimal('2067.86'))
(None, Decimal('4'), Decimal('10'), Decimal('1973.18'))
(None, Decimal('4'), Decimal('11'), Decimal('1940.32'))
(None, Decimal('4'), Decimal('12'), Decimal('1930.48'))
(None, Decimal('4'), Decimal('26'), Decimal('347.21'))
(None, Decimal('4'), Decimal('27'), Decimal('2673.57'))
(None, Decimal('4'), Decimal('28'), Decimal('2622.73'))
(None, Decimal('4'), Decimal('29'), Decimal('2717.60'))
(None, Decimal('4'), Decimal('30'), Decimal('5723.89'))
(None, Decimal('4'), None, Decimal('28559.46'))
(None, Decimal('5'), Decimal('14'), Decimal('514.18'))
(None, Decimal('5'), None, Decimal('514.18'))
(Decimal('2007'), None, Decimal('1'), Decimal('2808.24'))
(None, None, Decimal('1'), Decimal('2808.24'))
(Decimal('2007'), None, Decimal('2'), Decimal('2550.05'))
(None, None, Decimal('2'), Decimal('2550.05'))
(Decimal('2007'), None, Decimal('5'), Decimal('273.36'))
(None, None, Decimal('5'), Decimal('273.36'))
(Decimal('2007'), None, Decimal('6'), Decimal('2077.14'))
(None, None, Decimal('6'), Decimal('2077.14'))
(Decimal('2007'), None, Decimal('7'), Decimal('1984.28'))
(None, None, Decimal('7'), Decimal('1984.28'))
(Decimal('2007'), None, Decimal('8'), Decimal('2227.84'))
(None, None, Decimal('8'), Decimal('2227.84'))
(Decimal('2007'), None, Decimal('9'), Decimal('2067.86'))
(None, None, Decimal('9'), Decimal('2067.86'))
(Decimal('2007'), None, Decimal('10'), Decimal('1973.18'))
(None, None, Decimal('10'), Decimal('1973.18'))
(Decimal('2007'), None, Decimal('11'), Decimal('1940.32'))
(None, None, Decimal('11'), Decimal('1940.32'))
(Decimal('2007'), None, Decimal('12'), Decimal('1930.48'))
(None, None, Decimal('12'), Decimal('1930.48'))
(Decimal('2007'), None, Decimal('14'), Decimal('630.91'))
(None, None, Decimal('14'), Decimal('630.91'))
(Decimal('2007'), None, Decimal('15'), Decimal('1188.92'))
(None, None, Decimal('15'), Decimal('1188.92'))
(Decimal('2007'), None, Decimal('16'), Decimal('1453.46'))
(None, None, Decimal('16'), Decimal('1453.46'))
(Decimal('2007'), None, Decimal('17'), Decimal('3630.33'))
(None, None, Decimal('17'), Decimal('3630.33'))
(Decimal('2007'), None, Decimal('18'), Decimal('3977.74'))
(None, None, Decimal('18'), Decimal('3977.74'))
(Decimal('2007'), None, Decimal('19'), Decimal('3908.59'))
(None, None, Decimal('19'), Decimal('3908.59'))
(Decimal('2007'), None, Decimal('20'), Decimal('3888.98'))
(None, None, Decimal('20'), Decimal('3888.98'))
(Decimal('2007'), None, Decimal('21'), Decimal('3786.14'))
(None, None, Decimal('21'), Decimal('3786.14'))
(Decimal('2007'), None, Decimal('22'), Decimal('2586.79'))
(None, None, Decimal('22'), Decimal('2586.79'))
(Decimal('2007'), None, Decimal('23'), Decimal('2342.43'))
(None, None, Decimal('23'), Decimal('2342.43'))
(Decimal('2007'), None, Decimal('26'), Decimal('347.21'))
(None, None, Decimal('26'), Decimal('347.21'))
(Decimal('2007'), None, Decimal('27'), Decimal('2673.57'))
(None, None, Decimal('27'), Decimal('2673.57'))
(Decimal('2007'), None, Decimal('28'), Decimal('2622.73'))
(None, None, Decimal('28'), Decimal('2622.73'))
(Decimal('2007'), None, Decimal('29'), Decimal('2717.60'))
(None, None, Decimal('29'), Decimal('2717.60'))
(Decimal('2007'), None, Decimal('30'), Decimal('5723.89'))
(None, None, Decimal('30'), Decimal('5723.89'))

In [32]:
# forth question
import psycopg2


#establishing the connection
conn = psycopg2.connect(
   database='dvdrental', user='postgres', password='1', host='127.0.0.1', port= '5432'
)
cursor = conn.cursor()

sql ='''
    select 
    f.film_id, name as category_name, length,
    rank() over(partition by name order by length)
    
    from film f left join film_category fc on f.film_id=fc.film_id
    left join category c on c.category_id=fc.category_id
    ;
    
'''
cursor.execute(sql)

col_names = []
for elt in cursor.description:
    col_names.append(elt[0])
print(col_names)
result = cursor.fetchall()
for i in result:
    print(i)

conn.close()

['film_id', 'category_name', 'length', 'rank']
(869, 'Action', 47, 1)
(292, 'Action', 51, 2)
(542, 'Action', 52, 3)
(111, 'Action', 52, 3)
(794, 'Action', 52, 3)
(697, 'Action', 53, 6)
(97, 'Action', 56, 7)
(732, 'Action', 58, 8)
(303, 'Action', 58, 8)
(205, 'Action', 58, 8)
(586, 'Action', 60, 11)
(253, 'Action', 61, 12)
(964, 'Action', 61, 12)
(329, 'Action', 63, 14)
(911, 'Action', 64, 15)
(664, 'Action', 65, 16)
(38, 'Action', 68, 17)
(67, 'Action', 77, 18)
(968, 'Action', 79, 19)
(375, 'Action', 85, 20)
(574, 'Action', 86, 21)
(229, 'Action', 87, 22)
(915, 'Action', 92, 23)
(417, 'Action', 93, 24)
(162, 'Action', 95, 25)
(717, 'Action', 97, 26)
(360, 'Action', 103, 27)
(318, 'Action', 103, 27)
(194, 'Action', 104, 29)
(395, 'Action', 108, 30)
(530, 'Action', 108, 30)
(748, 'Action', 109, 32)
(659, 'Action', 109, 32)
(130, 'Action', 110, 34)
(838, 'Action', 112, 35)
(19, 'Action', 113, 36)
(105, 'Action', 125, 37)
(594, 'Action', 126, 38)
(982, 'Action', 126, 38)
(371, 'Action', 129, 40)
(56, 'Action', 129, 40)
(21, 'Action', 129, 40)
(210, 'Action', 130, 43)
(802, 'Action', 132, 44)
(252, 'Action', 135, 45)
(793, 'Action', 139, 46)
(501, 'Action', 141, 47)
(823, 'Action', 143, 48)
(271, 'Action', 148, 49)
(579, 'Action', 149, 50)
(327, 'Action', 158, 51)
(850, 'Action', 163, 52)
(825, 'Action', 165, 53)
(115, 'Action', 167, 54)
(29, 'Action', 168, 55)
(250, 'Action', 170, 56)
(549, 'Action', 171, 57)
(927, 'Action', 174, 58)
(511, 'Action', 175, 59)
(287, 'Action', 176, 60)
(707, 'Action', 177, 61)
(126, 'Action', 179, 62)
(212, 'Action', 185, 63)
(991, 'Action', 185, 63)
(243, 'Animation', 49, 1)
(430, 'Animation', 49, 1)
(134, 'Animation', 51, 3)
(402, 'Animation', 52, 4)
(489, 'Animation', 54, 5)
(849, 'Animation', 57, 6)
(18, 'Animation', 57, 6)
(743, 'Animation', 60, 8)
(816, 'Animation', 62, 9)
(89, 'Animation', 63, 10)
(805, 'Animation', 64, 11)
(160, 'Animation', 65, 12)
(326, 'Animation', 69, 13)
(541, 'Animation', 74, 14)
(223, 'Animation', 76, 15)
(963, 'Animation', 78, 16)
(470, 'Animation', 79, 17)
(916, 'Animation', 80, 18)
(154, 'Animation', 81, 19)
(651, 'Animation', 84, 20)
(118, 'Animation', 85, 21)
(78, 'Animation', 85, 21)
(986, 'Animation', 85, 21)
(649, 'Animation', 85, 21)
(208, 'Animation', 89, 25)
(314, 'Animation', 91, 26)
(23, 'Animation', 92, 27)
(433, 'Animation', 95, 28)
(268, 'Animation', 96, 29)
(703, 'Animation', 100, 30)
(355, 'Animation', 101, 31)
(300, 'Animation', 102, 32)
(892, 'Animation', 104, 33)
(464, 'Animation', 107, 34)
(330, 'Animation', 112, 35)
(953, 'Animation', 112, 35)
(859, 'Animation', 114, 37)
(696, 'Animation', 114, 37)
(644, 'Animation', 115, 39)
(693, 'Animation', 115, 39)
(259, 'Animation', 116, 41)
(239, 'Animation', 122, 42)
(461, 'Animation', 123, 43)
(241, 'Animation', 125, 44)
(36, 'Animation', 127, 45)
(887, 'Animation', 135, 46)
(865, 'Animation', 135, 46)
(70, 'Animation', 142, 48)
(901, 'Animation', 142, 48)
(325, 'Animation', 145, 50)
(569, 'Animation', 147, 51)
(121, 'Animation', 151, 52)
(880, 'Animation', 152, 53)
(193, 'Animation', 153, 54)
(564, 'Animation', 161, 55)
(582, 'Animation', 162, 56)
(583, 'Animation', 164, 57)
(456, 'Animation', 167, 58)
(245, 'Animation', 177, 59)
(692, 'Animation', 179, 60)
(615, 'Animation', 180, 61)
(510, 'Animation', 181, 62)
(886, 'Animation', 184, 63)
(820, 'Animation', 184, 63)
(349, 'Animation', 185, 65)
(690, 'Animation', 185, 65)
(505, 'Children', 46, 1)
(392, 'Children', 51, 2)
(66, 'Children', 53, 3)
(110, 'Children', 53, 3)
(883, 'Children', 53, 3)
(238, 'Children', 57, 6)
(626, 'Children', 57, 6)
(214, 'Children', 59, 8)
(409, 'Children', 59, 8)
(485, 'Children', 60, 10)
(688, 'Children', 61, 11)
(168, 'Children', 67, 12)
(423, 'Children', 69, 13)
(491, 'Children', 74, 14)
(509, 'Children', 78, 15)
(959, 'Children', 83, 16)
(928, 'Children', 84, 17)
(450, 'Children', 84, 17)
(354, 'Children', 85, 19)
(152, 'Children', 90, 20)
(864, 'Children', 92, 21)
(343, 'Children', 94, 22)
(468, 'Children', 97, 23)
(755, 'Children', 99, 24)
(999, 'Children', 101, 25)
(735, 'Children', 102, 26)
(356, 'Children', 102, 26)
(768, 'Children', 102, 26)
(852, 'Children', 103, 29)
(573, 'Children', 105, 30)
(873, 'Children', 108, 31)
(370, 'Children', 108, 31)
(889, 'Children', 111, 33)
(515, 'Children', 113, 34)
(786, 'Children', 113, 34)
(547, 'Children', 117, 36)
(48, 'Children', 118, 37)
(68, 'Children', 122, 38)
(304, 'Children', 130, 39)
(328, 'Children', 131, 40)
(833, 'Children', 134, 41)
(955, 'Children', 135, 42)
(553, 'Children', 136, 43)
(853, 'Children', 139, 44)
(191, 'Children', 143, 45)
(157, 'Children', 143, 45)
(424, 'Children', 149, 47)
(149, 'Children', 150, 48)
(918, 'Children', 152, 49)
(801, 'Children', 152, 49)
(761, 'Children', 154, 51)
(373, 'Children', 156, 52)
(896, 'Children', 157, 53)
(59, 'Children', 160, 54)
(124, 'Children', 163, 55)
(608, 'Children', 166, 56)
(588, 'Children', 175, 57)
(280, 'Children', 177, 58)
(344, 'Children', 178, 59)
(993, 'Children', 178, 59)
(469, 'Classics', 46, 1)
(970, 'Classics', 52, 2)
(862, 'Classics', 53, 3)
(548, 'Classics', 53, 3)
(633, 'Classics', 54, 5)
(536, 'Classics', 65, 6)
(196, 'Classics', 69, 7)
(891, 'Classics', 69, 7)
(116, 'Classics', 70, 9)
(611, 'Classics', 73, 10)
(815, 'Classics', 74, 11)
(537, 'Classics', 75, 12)
(951, 'Classics', 78, 13)
(828, 'Classics', 79, 14)
(341, 'Classics', 82, 15)
(480, 'Classics', 84, 16)
(471, 'Classics', 84, 16)
(808, 'Classics', 84, 16)
(962, 'Classics', 85, 19)
(425, 'Classics', 88, 20)
(60, 'Classics', 89, 21)
(744, 'Classics', 89, 21)
(184, 'Classics', 92, 23)
(14, 'Classics', 94, 24)
(694, 'Classics', 98, 25)
(91, 'Classics', 98, 25)
(663, 'Classics', 99, 27)
(445, 'Classics', 100, 28)
(482, 'Classics', 102, 29)
(512, 'Classics', 110, 30)
(357, 'Classics', 114, 31)
(37, 'Classics', 121, 32)
(297, 'Classics', 122, 33)
(487, 'Classics', 124, 34)
(652, 'Classics', 126, 35)
(346, 'Classics', 128, 36)
(950, 'Classics', 132, 37)
(432, 'Classics', 139, 38)
(525, 'Classics', 140, 39)
(266, 'Classics', 141, 40)
(895, 'Classics', 142, 41)
(578, 'Classics', 142, 41)
(843, 'Classics', 143, 43)
(228, 'Classics', 143, 43)
(899, 'Classics', 144, 45)
(166, 'Classics', 149, 46)
(131, 'Classics', 152, 47)
(731, 'Classics', 153, 48)
(874, 'Classics', 155, 49)
(554, 'Classics', 159, 50)
(358, 'Classics', 163, 51)
(725, 'Classics', 167, 52)
(190, 'Classics', 172, 53)
(484, 'Classics', 172, 53)
(523, 'Classics', 174, 55)
(249, 'Classics', 176, 56)
(180, 'Classics', 184, 57)
(247, 'Comedy', 47, 1)
(410, 'Comedy', 48, 2)
(657, 'Comedy', 48, 2)
(443, 'Comedy', 49, 4)
(524, 'Comedy', 50, 5)
(1000, 'Comedy', 50, 5)
(159, 'Comedy', 58, 7)
(7, 'Comedy', 62, 8)
(529, 'Comedy', 67, 9)
(242, 'Comedy', 68, 10)
(388, 'Comedy', 70, 11)
(502, 'Comedy', 71, 12)
(932, 'Comedy', 73, 13)
(568, 'Comedy', 77, 14)
(756, 'Comedy', 80, 15)
(672, 'Comedy', 82, 16)
(444, 'Comedy', 83, 17)
(837, 'Comedy', 85, 18)
(939, 'Comedy', 90, 19)
(28, 'Comedy', 91, 20)
(613, 'Comedy', 92, 21)
(978, 'Comedy', 98, 22)
(680, 'Comedy', 103, 23)
(404, 'Comedy', 107, 24)
(660, 'Comedy', 107, 24)
(814, 'Comedy', 110, 26)
(478, 'Comedy', 112, 27)
(127, 'Comedy', 112, 27)
(178, 'Comedy', 115, 29)
(276, 'Comedy', 115, 29)
(704, 'Comedy', 121, 31)
(858, 'Comedy', 127, 32)
(905, 'Comedy', 132, 33)
(335, 'Comedy', 133, 34)
(555, 'Comedy', 133, 34)
(99, 'Comedy', 136, 36)
(188, 'Comedy', 136, 36)
(522, 'Comedy', 137, 38)
(385, 'Comedy', 139, 39)
(308, 'Comedy', 142, 40)
(857, 'Comedy', 144, 41)
(324, 'Comedy', 148, 42)
(317, 'Comedy', 148, 42)
(754, 'Comedy', 150, 44)
(365, 'Comedy', 154, 45)
(638, 'Comedy', 156, 46)
(332, 'Comedy', 159, 47)
(604, 'Comedy', 160, 48)
(202, 'Comedy', 161, 49)
(265, 'Comedy', 168, 50)
(413, 'Comedy', 169, 51)
(906, 'Comedy', 171, 52)
(938, 'Comedy', 173, 53)
(871, 'Comedy', 176, 54)
(119, 'Comedy', 176, 54)
(774, 'Comedy', 182, 56)
(765, 'Comedy', 182, 56)
(182, 'Comedy', 185, 58)
(407, 'Documentary', 47, 1)
(393, 'Documentary', 47, 1)
(575, 'Documentary', 48, 3)
(670, 'Documentary', 48, 3)
(3, 'Documentary', 50, 5)
(812, 'Documentary', 50, 5)
(219, 'Documentary', 51, 7)
(888, 'Documentary', 53, 8)
(497, 'Documentary', 54, 9)
(164, 'Documentary', 55, 10)
(199, 'Documentary', 56, 11)
(85, 'Documentary', 63, 12)
(466, 'Documentary', 63, 12)
(627, 'Documentary', 67, 14)
(274, 'Documentary', 67, 14)
(966, 'Documentary', 70, 16)
(698, 'Documentary', 71, 17)
(400, 'Documentary', 72, 18)
(101, 'Documentary', 73, 19)
(713, 'Documentary', 74, 20)
(589, 'Documentary', 74, 20)
(943, 'Documentary', 76, 22)
(587, 'Documentary', 77, 23)
(712, 'Documentary', 82, 24)
(1, 'Documentary', 86, 25)
(776, 'Documentary', 90, 26)
(616, 'Documentary', 92, 27)
(72, 'Documentary', 93, 28)
(295, 'Documentary', 97, 29)
(336, 'Documentary', 99, 30)
(221, 'Documentary', 100, 31)
(150, 'Documentary', 101, 32)
(412, 'Documentary', 102, 33)
(427, 'Documentary', 103, 34)
(788, 'Documentary', 104, 35)
(757, 'Documentary', 106, 36)
(62, 'Documentary', 106, 36)
(708, 'Documentary', 112, 38)
(926, 'Documentary', 120, 39)
(58, 'Documentary', 122, 40)
(142, 'Documentary', 122, 40)
(576, 'Documentary', 122, 40)
(441, 'Documentary', 125, 43)
(960, 'Documentary', 128, 44)
(629, 'Documentary', 128, 44)
(552, 'Documentary', 130, 46)
(855, 'Documentary', 132, 47)
(687, 'Documentary', 138, 48)
(206, 'Documentary', 144, 49)
(650, 'Documentary', 144, 49)
(544, 'Documentary', 147, 51)
(40, 'Documentary', 148, 52)
(834, 'Documentary', 151, 53)
(952, 'Documentary', 152, 54)
(457, 'Documentary', 157, 55)
(734, 'Documentary', 158, 56)
(622, 'Documentary', 159, 57)
(571, 'Documentary', 161, 58)
(156, 'Documentary', 164, 59)
(925, 'Documentary', 164, 59)
(945, 'Documentary', 164, 59)
(791, 'Documentary', 167, 62)
(261, 'Documentary', 171, 63)
(992, 'Documentary', 176, 64)
(248, 'Documentary', 177, 65)
(129, 'Documentary', 179, 66)
(973, 'Documentary', 183, 67)
(996, 'Documentary', 183, 67)
(504, 'Drama', 46, 1)
(630, 'Drama', 48, 2)
(683, 'Drama', 60, 3)
(396, 'Drama', 62, 4)
(728, 'Drama', 63, 5)
(107, 'Drama', 63, 5)
(186, 'Drama', 64, 7)
(173, 'Drama', 65, 8)
(790, 'Drama', 67, 9)
(514, 'Drama', 69, 10)
(98, 'Drama', 73, 11)
(225, 'Drama', 76, 12)
(923, 'Drama', 78, 13)
(772, 'Drama', 80, 14)
(766, 'Drama', 84, 15)
(368, 'Drama', 84, 15)
(910, 'Drama', 87, 17)
(282, 'Drama', 92, 18)
(366, 'Drama', 93, 19)
(882, 'Drama', 99, 20)
(209, 'Drama', 99, 20)
(979, 'Drama', 100, 22)
(585, 'Drama', 105, 23)
(204, 'Drama', 106, 24)
(230, 'Drama', 107, 25)
(146, 'Drama', 107, 25)
(775, 'Drama', 110, 27)
(172, 'Drama', 112, 28)
(79, 'Drama', 114, 29)
(662, 'Drama', 118, 30)
(643, 'Drama', 118, 30)
(403, 'Drama', 121, 32)
(218, 'Drama', 122, 33)
(758, 'Drama', 125, 34)
(618, 'Drama', 132, 35)
(771, 'Drama', 137, 36)
(827, 'Drama', 141, 37)
(143, 'Drama', 142, 38)
(666, 'Drama', 145, 39)
(739, 'Drama', 145, 39)
(709, 'Drama', 147, 41)
(521, 'Drama', 147, 41)
(439, 'Drama', 151, 43)
(64, 'Drama', 151, 43)
(539, 'Drama', 152, 45)
(272, 'Drama', 153, 46)
(33, 'Drama', 153, 46)
(418, 'Drama', 157, 48)
(969, 'Drama', 159, 49)
(706, 'Drama', 163, 50)
(379, 'Drama', 166, 51)
(401, 'Drama', 168, 52)
(907, 'Drama', 168, 52)
(179, 'Drama', 173, 54)
(942, 'Drama', 174, 55)
(61, 'Drama', 175, 56)
(958, 'Drama', 178, 57)
(803, 'Drama', 179, 58)
(897, 'Drama', 179, 58)
(944, 'Drama', 179, 58)
(818, 'Drama', 180, 61)
(473, 'Drama', 181, 62)
(866, 'Family', 48, 1)
(753, 'Family', 48, 1)
(634, 'Family', 48, 1)
(617, 'Family', 50, 4)
(83, 'Family', 50, 4)
(679, 'Family', 50, 4)
(824, 'Family', 52, 7)
(603, 'Family', 53, 8)
(867, 'Family', 58, 9)
(231, 'Family', 63, 10)
(442, 'Family', 65, 11)
(534, 'Family', 70, 12)
(82, 'Family', 71, 13)
(63, 'Family', 73, 14)
(550, 'Family', 74, 15)
(621, 'Family', 75, 16)
(348, 'Family', 86, 17)
(53, 'Family', 87, 18)
(639, 'Family', 92, 19)
(31, 'Family', 92, 19)
(269, 'Family', 98, 21)
(309, 'Family', 98, 21)
(780, 'Family', 98, 21)
(71, 'Family', 100, 24)
(147, 'Family', 101, 25)
(213, 'Family', 104, 26)
(273, 'Family', 107, 27)
(778, 'Family', 109, 28)
(437, 'Family', 109, 28)
(724, 'Family', 110, 30)
(795, 'Family', 111, 31)
(183, 'Family', 112, 32)
(139, 'Family', 114, 33)
(700, 'Family', 115, 34)
(727, 'Family', 117, 35)
(262, 'Family', 119, 36)
(710, 'Family', 120, 37)
(175, 'Family', 122, 38)
(145, 'Family', 124, 39)
(479, 'Family', 128, 40)
(610, 'Family', 129, 41)
(5, 'Family', 130, 42)
(476, 'Family', 130, 42)
(736, 'Family', 134, 44)
(682, 'Family', 134, 44)
(377, 'Family', 135, 46)
(458, 'Family', 135, 46)
(975, 'Family', 137, 48)
(829, 'Family', 138, 49)
(419, 'Family', 141, 50)
(428, 'Family', 141, 50)
(946, 'Family', 144, 52)
(695, 'Family', 144, 52)
(391, 'Family', 146, 54)
(715, 'Family', 147, 55)
(810, 'Family', 147, 55)
(80, 'Family', 148, 57)
(528, 'Family', 155, 58)
(315, 'Family', 156, 59)
(345, 'Family', 161, 60)
(498, 'Family', 161, 60)
(822, 'Family', 169, 62)
(43, 'Family', 170, 63)
(359, 'Family', 173, 64)
(832, 'Family', 175, 65)
(94, 'Family', 176, 66)
(557, 'Family', 177, 67)
(50, 'Family', 182, 68)
(499, 'Family', 184, 69)
(15, 'Foreign', 46, 1)
(845, 'Foreign', 48, 2)
(607, 'Foreign', 50, 3)
(192, 'Foreign', 50, 3)
(565, 'Foreign', 56, 5)
(947, 'Foreign', 59, 6)
(486, 'Foreign', 59, 6)
(726, 'Foreign', 61, 8)
(311, 'Foreign', 72, 9)
(566, 'Foreign', 72, 9)
(337, 'Foreign', 73, 11)
(459, 'Foreign', 74, 12)
(669, 'Foreign', 74, 12)
(623, 'Foreign', 75, 14)
(414, 'Foreign', 75, 14)
(641, 'Foreign', 76, 16)
(421, 'Foreign', 78, 17)
(789, 'Foreign', 79, 18)
(957, 'Foreign', 80, 19)
(567, 'Foreign', 80, 19)
(595, 'Foreign', 83, 21)
(705, 'Foreign', 88, 22)
(493, 'Foreign', 92, 23)
(533, 'Foreign', 98, 24)
(674, 'Foreign', 99, 25)
(399, 'Foreign', 100, 26)
(640, 'Foreign', 102, 27)
(455, 'Foreign', 103, 28)
(440, 'Foreign', 105, 29)
(971, 'Foreign', 109, 30)
(416, 'Foreign', 110, 31)
(908, 'Foreign', 110, 31)
(104, 'Foreign', 119, 33)
(112, 'Foreign', 120, 34)
(170, 'Foreign', 120, 34)
(207, 'Foreign', 121, 36)
(452, 'Foreign', 122, 37)
(353, 'Foreign', 125, 38)
(984, 'Foreign', 126, 39)
(11, 'Foreign', 126, 39)
(929, 'Foreign', 128, 41)
(148, 'Foreign', 132, 42)
(900, 'Foreign', 136, 43)
(531, 'Foreign', 137, 44)
(689, 'Foreign', 137, 44)
(185, 'Foreign', 146, 46)
(770, 'Foreign', 147, 47)
(769, 'Foreign', 151, 48)
(47, 'Foreign', 153, 49)
(246, 'Foreign', 154, 50)
(792, 'Foreign', 154, 50)
(376, 'Foreign', 155, 52)
(661, 'Foreign', 157, 53)
(605, 'Foreign', 157, 53)
(961, 'Foreign', 161, 55)
(100, 'Foreign', 161, 55)
(290, 'Foreign', 163, 57)
(500, 'Foreign', 163, 57)
(6, 'Foreign', 169, 59)
(52, 'Foreign', 173, 60)
(431, 'Foreign', 176, 61)
(201, 'Foreign', 176, 61)
(380, 'Foreign', 176, 61)
(738, 'Foreign', 178, 64)
(545, 'Foreign', 178, 64)
(460, 'Foreign', 178, 64)
(16, 'Foreign', 180, 67)
(584, 'Foreign', 180, 67)
(467, 'Foreign', 181, 69)
(435, 'Foreign', 181, 69)
(128, 'Foreign', 183, 71)
(198, 'Foreign', 184, 72)
(821, 'Foreign', 184, 72)
(215, 'Games', 57, 1)
(106, 'Games', 61, 2)
(560, 'Games', 62, 3)
(438, 'Games', 68, 4)
(408, 'Games', 69, 5)
(840, 'Games', 75, 6)
(919, 'Games', 82, 7)
(807, 'Games', 87, 8)
(227, 'Games', 88, 9)
(331, 'Games', 90, 10)
(654, 'Games', 93, 11)
(546, 'Games', 98, 12)
(387, 'Games', 100, 13)
(236, 'Games', 100, 13)
(742, 'Games', 101, 15)
(264, 'Games', 101, 15)
(306, 'Games', 104, 17)
(699, 'Games', 106, 18)
(956, 'Games', 107, 19)
(46, 'Games', 108, 20)
(861, 'Games', 111, 21)
(976, 'Games', 111, 21)
(835, 'Games', 112, 23)
(507, 'Games', 113, 24)
(842, 'Games', 113, 24)
(362, 'Games', 115, 26)
(746, 'Games', 118, 27)
(217, 'Games', 120, 28)
(934, 'Games', 122, 29)
(781, 'Games', 127, 30)
(556, 'Games', 127, 30)
(302, 'Games', 131, 32)
(447, 'Games', 131, 32)
(200, 'Games', 133, 34)
(117, 'Games', 135, 35)
(382, 'Games', 137, 36)
(189, 'Games', 139, 37)
(281, 'Games', 143, 38)
(508, 'Games', 144, 39)
(941, 'Games', 145, 40)
(232, 'Games', 147, 41)
(624, 'Games', 149, 42)
(381, 'Games', 150, 43)
(762, 'Games', 154, 44)
(701, 'Games', 155, 45)
(949, 'Games', 157, 46)
(310, 'Games', 158, 47)
(563, 'Games', 165, 48)
(211, 'Games', 165, 48)
(646, 'Games', 169, 50)
(596, 'Games', 171, 51)
(483, 'Games', 171, 51)
(747, 'Games', 171, 51)
(316, 'Games', 173, 54)
(684, 'Games', 173, 54)
(352, 'Games', 176, 56)
(614, 'Games', 178, 57)
(406, 'Games', 181, 58)
(591, 'Games', 182, 59)
(597, 'Games', 184, 60)
(141, 'Games', 185, 61)
(2, 'Horror', 48, 1)
(799, 'Horror', 51, 2)
(8, 'Horror', 54, 3)
(171, 'Horror', 59, 4)
(34, 'Horror', 62, 5)
(222, 'Horror', 64, 6)
(334, 'Horror', 65, 7)
(506, 'Horror', 67, 8)
(881, 'Horror', 71, 9)
(904, 'Horror', 71, 9)
(92, 'Horror', 72, 11)
(856, 'Horror', 73, 12)
(30, 'Horror', 82, 13)
(415, 'Horror', 84, 14)
(275, 'Horror', 85, 15)
(527, 'Horror', 85, 15)
(995, 'Horror', 86, 17)
(702, 'Horror', 89, 18)
(876, 'Horror', 91, 19)
(258, 'Horror', 96, 20)
(65, 'Horror', 100, 21)
(909, 'Horror', 102, 22)
(653, 'Horror', 102, 22)
(737, 'Horror', 102, 22)
(998, 'Horror', 105, 25)
(351, 'Horror', 106, 26)
(922, 'Horror', 107, 27)
(965, 'Horror', 112, 28)
(9, 'Horror', 114, 29)
(122, 'Horror', 114, 29)
(4, 'Horror', 117, 31)
(313, 'Horror', 118, 32)
(854, 'Horror', 119, 33)
(494, 'Horror', 120, 34)
(658, 'Horror', 121, 35)
(722, 'Horror', 123, 36)
(870, 'Horror', 123, 36)
(800, 'Horror', 126, 38)
(277, 'Horror', 126, 38)
(804, 'Horror', 129, 40)
(475, 'Horror', 135, 41)
(716, 'Horror', 136, 42)
(35, 'Horror', 147, 43)
(830, 'Horror', 149, 44)
(13, 'Horror', 150, 45)
(740, 'Horror', 153, 46)
(749, 'Horror', 153, 46)
(301, 'Horror', 155, 48)
(593, 'Horror', 158, 49)
(600, 'Horror', 166, 50)
(495, 'Horror', 169, 51)
(990, 'Horror', 171, 52)
(665, 'Horror', 175, 53)
(885, 'Horror', 179, 54)
(24, 'Horror', 181, 55)
(535, 'Horror', 181, 55)
(398, 'Music', 47, 1)
(411, 'Music', 49, 2)
(384, 'Music', 49, 2)
(363, 'Music', 54, 4)
(581, 'Music', 59, 5)
(516, 'Music', 59, 5)
(877, 'Music', 64, 7)
(797, 'Music', 67, 8)
(161, 'Music', 70, 9)
(718, 'Music', 73, 10)
(980, 'Music', 75, 11)
(51, 'Music', 75, 11)
(284, 'Music', 77, 13)
(462, 'Music', 78, 14)
(20, 'Music', 79, 15)
(741, 'Music', 81, 16)
(17, 'Music', 82, 17)
(884, 'Music', 88, 18)
(378, 'Music', 93, 19)
(540, 'Music', 97, 20)
(752, 'Music', 101, 21)
(76, 'Music', 103, 22)
(983, 'Music', 105, 23)
(220, 'Music', 106, 24)
(592, 'Music', 107, 25)
(54, 'Music', 113, 26)
(987, 'Music', 116, 27)
(133, 'Music', 117, 28)
(673, 'Music', 118, 29)
(477, 'Music', 118, 29)
(86, 'Music', 121, 31)
(936, 'Music', 123, 32)
(158, 'Music', 124, 33)
(333, 'Music', 126, 34)
(647, 'Music', 129, 35)
(12, 'Music', 136, 36)
(244, 'Music', 139, 37)
(879, 'Music', 148, 38)
(562, 'Music', 151, 39)
(278, 'Music', 155, 40)
(636, 'Music', 161, 41)
(74, 'Music', 162, 42)
(819, 'Music', 165, 43)
(921, 'Music', 172, 44)
(255, 'Music', 175, 45)
(997, 'Music', 179, 46)
(174, 'Music', 180, 47)
(454, 'Music', 180, 47)
(721, 'Music', 182, 49)
(767, 'Music', 183, 50)
(426, 'Music', 185, 51)
(730, 'New', 46, 1)
(226, 'New', 56, 2)
(481, 'New', 58, 3)
(635, 'New', 58, 3)
(465, 'New', 59, 5)
(675, 'New', 60, 6)
(144, 'New', 61, 7)
(77, 'New', 61, 7)
(920, 'New', 62, 9)
(90, 'New', 63, 10)
(289, 'New', 66, 11)
(108, 'New', 67, 12)
(558, 'New', 71, 13)
(759, 'New', 73, 14)
(954, 'New', 73, 14)
(364, 'New', 73, 14)
(25, 'New', 74, 17)
(320, 'New', 80, 18)
(45, 'New', 83, 19)
(686, 'New', 84, 20)
(270, 'New', 85, 21)
(22, 'New', 85, 21)
(937, 'New', 85, 21)
(283, 'New', 85, 21)
(109, 'New', 89, 25)
(305, 'New', 91, 26)
(846, 'New', 93, 27)
(994, 'New', 100, 28)
(760, 'New', 110, 29)
(216, 'New', 113, 30)
(913, 'New', 115, 31)
(32, 'New', 119, 32)
(490, 'New', 121, 33)
(93, 'New', 121, 33)
(436, 'New', 122, 35)
(95, 'New', 123, 36)
(561, 'New', 123, 36)
(321, 'New', 123, 36)
(933, 'New', 126, 39)
(685, 'New', 132, 40)
(251, 'New', 133, 41)
(492, 'New', 134, 42)
(590, 'New', 135, 43)
(677, 'New', 136, 44)
(806, 'New', 137, 45)
(551, 'New', 138, 46)
(163, 'New', 139, 47)
(948, 'New', 139, 47)
(267, 'New', 140, 49)
(935, 'New', 142, 50)
(632, 'New', 145, 51)
(750, 'New', 145, 51)
(136, 'New', 146, 53)